### ISSUE TITLE
Is "application.name" in application.conf necessary?

### ISSUE THREAD

**Issue by philipmjohnson** [playframework/play-ebean-example#2]
The application.conf file contains the following line:

```
application.name=computer-database
```

This variable is never referenced anyplace and I am not sure of its function. Could it be documented inside application.conf or else removed to avoid confusion?

**Comment by adis-me** [comment]
Sample configuration: https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/reference.conf

I cannot see `application.name`,  I have never used it nor seen it before.
