### ISSUE TITLE
Error: java: the package routes not exist!

### ISSUE THREAD

**Issue by fusuipu** [playframework/play-ebean-example#24]
when l run this example in intelij, it failed this the following error, can you give me some guides?
Error:(31, 19) java: the package routes not exist!
Error:(51, 27) java: symbol not found!
  symbol :   class  list
  place: package views.html

**Comment by keenan-v1** [comment]
I noticed this was closed without a response. You need to use sbt to build your project. IntelliJ offers this by going into the Build settings and under sbt you can check the box to use sbt console for build and import.
