### ISSUE TITLE
Evolution Play Ebean Example

### ISSUE THREAD

**Issue by placebocurejava** [playframework/play-ebean-example#5]
Hi Sir. Sargent,

I wish I could give this example of the <Computer Database> more efficient and adaptable but I'm stuck ... Could you please help us to add multiple deletion via multiple checkboxes by Selecting / Deselcting ?

it would be very kind of you. Thank you in advance.

![sans titre](https://cloud.githubusercontent.com/assets/18368701/16457696/f23449a4-3e0b-11e6-8723-b5df22fac751.png)

**Comment by marcospereira** [comment]
Hello @placebocurejava,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in play-ebean, not for general discussion and getting help.

**Comment by placebocurejava** [comment]
Hi,

No matter if the issue is closed and it is understood :) but....could you
juste tell me if you had already seen a sample that offers that kind of
example please....I am really stuck on this.
thank you so much...

**Comment by wsargent** [comment]
Hi all -- placebocurejava has been banned from playframework, as he was posting on the google group with stolen credentials. His comments have been removed. Please see https://groups.google.com/forum/#!topic/play-framework/5FCht0abCI4 for more information.
