### ISSUE TITLE
Question about controllers for many pages

### ISSUE THREAD

**Issue by HannahJSwystun** [playframework/play-ebean-example#57]
Hello,

I would like to ask a simple question about the fact if i create many pages, should i create many controllers.java ?

For example, here the sample is about one page, so, there is one HomeController.java for methods index,edit,delete,...

what about a big project who has many pages? should i create a controller_1.java, controller_2.java....for each page ?

Thank you

**Comment by marcospereira** [comment]
Hi, @HannahJSwystun.

If you are delivering dynamic content, then the recommendation is to have distinct actions for each page. But this is not a strict rule and you can of somehow delivery multiple pages using the action, although this is not a best practice (not related to Play, but [how to structure methods](https://ncrcoe.gitbooks.io/java-for-small-teams/content/style/400_methods_should_do_one_thing.html)).

And, of course, a single controller can have more than one action. I think a good rule related to how to structure controllers is thinking about [REST resources](http://restful-api-design.readthedocs.io/en/latest/resources.html) and have one controller per resource. For example, if you have an `Article` resource, you can have a controller like:

```java
public class ArticlesController extends Controller {
   public Result list() { ... }
   public Result show(Long id) { ... }
   public Result update(Long id) { ... }
   public Result create() { ... }
}
```
Again, this is not a strict rule and there is nothing preventing you to create a controller for each page.

Finally, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.
