### ISSUE TITLE
More Filters

### ISSUE THREAD

**Issue by HannahJSwystun** [playframework/play-ebean-example#6]
Hello,

Could you please tell me how to add theses filters : 
1- Filter by ID-COMPUTER
2- Filter by ID-COMPUTER
3- Add custom SQL query ( select \* from computers join company on.....etc )

Thank you in advance.

**Comment by marcospereira** [comment]
@HannahJSwystun this is just an example application. You can ask questions about it at the [mailing list](https://groups.google.com/forum/#!forum/play-framework).
